name: rpmtw_wiki
description: RPMTW Wiki Client.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  rpmtw_api_client_flutter: ^1.0.6+2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  no_context_navigation: ^2.1.2
  font_awesome_flutter: ^9.2.0
  seo_renderer: ^0.3.0
  picture_verification_code: ^1.0.0
  another_flushbar: ^1.10.28
  flutter_markdown: ^0.6.9
  split_view: ^3.1.0
  undo: ^1.4.0
  http: ^0.13.4
  file_picker: ^4.3.2
  rate_limiter: ^0.1.1
  url_launcher: ^6.0.18

  # TODO: 支援 IO 端 (Android/iOS/Windows/Linux/Mac)

  universal_html: ^2.0.8
  universal_io: ^2.0.4
  share_plus: ^3.0.4
  url_strategy: ^0.2.0
  diff_match_patch: ^0.4.1
  flutter_svg: ^1.0.3
  carousel_slider: ^4.0.0
  firebase_analytics: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: font
      fonts:
        - asset: assets/fonts/NotoSansCJKtc-Regular.otf #Source: https://fonts.google.com/noto
