name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
  schedule:
    - cron: "*/60 0 * * *" #每天執行一次

jobs:
  Web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache flutter
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-2.10.0-0.3.pre
      - uses: subosito/flutter-action@master
        with:
          channel: beta
          flutter-version: 2.10.0-0.3.pre
      - name: SEO fetch wiki mods
        run: |
          cd script/seo_fetch_mods
          dart pub get
          dart run bin/seo_fetch_mods.dart
      - uses: bluefireteam/flutter-gh-pages@v7